//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Browser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Browser.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows read/write access to the &apos;properties&apos; table in the checkin database, to change values that get uploaded.
        /// </summary>
        internal static string ACCESS_CHECKIN_PROPERTIES {
            get {
                return ResourceManager.GetString("ACCESS_CHECKIN_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows an app to access approximate location derived from network location sources such as cell towers and Wi-Fi.
        /// </summary>
        internal static string ACCESS_COARSE_LOCATION {
            get {
                return ResourceManager.GetString("ACCESS_COARSE_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows an app to access precise location from location sources such as GPS, cell towers, and Wi-Fi.
        /// </summary>
        internal static string ACCESS_FINE_LOCATION {
            get {
                return ResourceManager.GetString("ACCESS_FINE_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows an application to access extra location provider commands.
        /// </summary>
        internal static string ACCESS_LOCATION_EXTRA_COMMANDS {
            get {
                return ResourceManager.GetString("ACCESS_LOCATION_EXTRA_COMMANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows an application to create mock location providers for testing.
        /// </summary>
        internal static string ACCESS_MOCK_LOCATION {
            get {
                return ResourceManager.GetString("ACCESS_MOCK_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows applications to access information about networks.
        /// </summary>
        internal static string ACCESS_NETWORK_STATE {
            get {
                return ResourceManager.GetString("ACCESS_NETWORK_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows an application to use SurfaceFlinger&apos;s low level features.
        /// </summary>
        internal static string ACCESS_SURFACE_FLINGER {
            get {
                return ResourceManager.GetString("ACCESS_SURFACE_FLINGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows applications to access information about Wi-Fi networks.
        /// </summary>
        internal static string ACCESS_WIFI_STATE {
            get {
                return ResourceManager.GetString("ACCESS_WIFI_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows applications to call into AccountAuthenticators.
        /// </summary>
        internal static string ACCOUNT_MANAGER {
            get {
                return ResourceManager.GetString("ACCOUNT_MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows an application to add voicemails into the system.
        /// </summary>
        internal static string ADD_VOICEMAIL {
            get {
                return ResourceManager.GetString("ADD_VOICEMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Snippet.
        /// </summary>
        internal static string AddSnippet {
            get {
                return ResourceManager.GetString("AddSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your vote for this Comment.
        /// </summary>
        internal static string AddYourVoteForThisComment {
            get {
                return ResourceManager.GetString("AddYourVoteForThisComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation for all copied to clipboard (RTF).
        /// </summary>
        internal static string AllDocumentationCopied {
            get {
                return ResourceManager.GetString("AllDocumentationCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android Packages.
        /// </summary>
        internal static string AndroidPackages {
            get {
                return ResourceManager.GetString("AndroidPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation.
        /// </summary>
        internal static string Annotation {
            get {
                return ResourceManager.GetString("Annotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arduino.
        /// </summary>
        internal static string Arduino {
            get {
                return ResourceManager.GetString("Arduino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arduino API.
        /// </summary>
        internal static string ArduinoAPI {
            get {
                return ResourceManager.GetString("ArduinoAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?  This operation will take a long time and cannot be interrupted..
        /// </summary>
        internal static string AreYouSureLongTimeOperation {
            get {
                return ResourceManager.GetString("AreYouSureLongTimeOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As.
        /// </summary>
        internal static string As {
            get {
                return ResourceManager.GetString("As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows an application to act as an AccountAuthenticator for the AccountManager.
        /// </summary>
        internal static string AUTHENTICATE_ACCOUNTS {
            get {
                return ResourceManager.GetString("AUTHENTICATE_ACCOUNTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B4a Forum.
        /// </summary>
        internal static string B4aForum {
            get {
                return ResourceManager.GetString("B4aForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B4a Help.
        /// </summary>
        internal static string B4aHelp {
            get {
                return ResourceManager.GetString("B4aHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B4a Object Browser.
        /// </summary>
        internal static string B4aObjectBrowser {
            get {
                return ResourceManager.GetString("B4aObjectBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B4a Object Browser (Community Content Enabled).
        /// </summary>
        internal static string B4aObjectBrowserCommunityContentEnabled {
            get {
                return ResourceManager.GetString("B4aObjectBrowserCommunityContentEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B4x Site Search.
        /// </summary>
        internal static string B4aSiteSearch {
            get {
                return ResourceManager.GetString("B4aSiteSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B4i Help.
        /// </summary>
        internal static string B4iHelp {
            get {
                return ResourceManager.GetString("B4iHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B4j Help.
        /// </summary>
        internal static string B4jHelp {
            get {
                return ResourceManager.GetString("B4jHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B4r Help.
        /// </summary>
        internal static string B4RHelp {
            get {
                return ResourceManager.GetString("B4RHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B4x Code Snippets.
        /// </summary>
        internal static string B4xCodeSnippets {
            get {
                return ResourceManager.GetString("B4xCodeSnippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B4x Forum.
        /// </summary>
        internal static string B4xForum {
            get {
                return ResourceManager.GetString("B4xForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B4x Help.
        /// </summary>
        internal static string B4xHelp {
            get {
                return ResourceManager.GetString("B4xHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B4x Object Browser.
        /// </summary>
        internal static string B4xObjectBrowser {
            get {
                return ResourceManager.GetString("B4xObjectBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B4x Object Browser Community Content Enabled.
        /// </summary>
        internal static string B4xObjectBrowserCommunityContentEnabled {
            get {
                return ResourceManager.GetString("B4xObjectBrowserCommunityContentEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows an application to collect battery statistics.
        /// </summary>
        internal static string BATTERY_STATS {
            get {
                return ResourceManager.GetString("BATTERY_STATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be required by an AccessibilityService, to ensure that only the system can bind to it.
        /// </summary>
        internal static string BIND_ACCESSIBILITY_SERVICE {
            get {
                return ResourceManager.GetString("BIND_ACCESSIBILITY_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows an application to tell the AppWidget service which application can access AppWidget&apos;s data.
        /// </summary>
        internal static string BIND_APPWIDGET {
            get {
                return ResourceManager.GetString("BIND_APPWIDGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be required by device administration receiver, to ensure that only the system can interact with it.
        /// </summary>
        internal static string BIND_DEVICE_ADMIN {
            get {
                return ResourceManager.GetString("BIND_DEVICE_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be required by an InputMethodService, to ensure that only the system can bind to it.
        /// </summary>
        internal static string BIND_INPUT_METHOD {
            get {
                return ResourceManager.GetString("BIND_INPUT_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be required by a RemoteViewsService, to ensure that only the system can bind to it.
        /// </summary>
        internal static string BIND_REMOTEVIEWS {
            get {
                return ResourceManager.GetString("BIND_REMOTEVIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be required by a TextService.
        /// </summary>
        internal static string BIND_TEXT_SERVICE {
            get {
                return ResourceManager.GetString("BIND_TEXT_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be required by a VpnService, to ensure that only the system can bind to it.
        /// </summary>
        internal static string BIND_VPN_SERVICE {
            get {
                return ResourceManager.GetString("BIND_VPN_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be required by a WallpaperService, to ensure that only the system can bind to it.
        /// </summary>
        internal static string BIND_WALLPAPER {
            get {
                return ResourceManager.GetString("BIND_WALLPAPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows applications to connect to paired bluetooth devices.
        /// </summary>
        internal static string BLUETOOTH {
            get {
                return ResourceManager.GetString("BLUETOOTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows applications to discover and pair bluetooth devices.
        /// </summary>
        internal static string BLUETOOTH_ADMIN {
            get {
                return ResourceManager.GetString("BLUETOOTH_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required to be able to disable the device (very dangerous!).
        /// </summary>
        internal static string BRICK {
            get {
                return ResourceManager.GetString("BRICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows an application to broadcast a notification that an application package has been removed.
        /// </summary>
        internal static string BROADCAST_PACKAGE_REMOVED {
            get {
                return ResourceManager.GetString("BROADCAST_PACKAGE_REMOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows an application to broadcast an SMS receipt notification.
        /// </summary>
        internal static string BROADCAST_SMS {
            get {
                return ResourceManager.GetString("BROADCAST_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows an application to broadcast sticky intents.
        /// </summary>
        internal static string BROADCAST_STICKY {
            get {
                return ResourceManager.GetString("BROADCAST_STICKY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows an application to broadcast a WAP PUSH receipt notification.
        /// </summary>
        internal static string BROADCAST_WAP_PUSH {
            get {
                return ResourceManager.GetString("BROADCAST_WAP_PUSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy me a Beer.
        /// </summary>
        internal static string BuymeaBeer {
            get {
                return ResourceManager.GetString("BuymeaBeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows an application to initiate a phone call without going through the Dialer user interface for the user to confirm the call being placed.
        /// </summary>
        internal static string CALL_PHONE {
            get {
                return ResourceManager.GetString("CALL_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows an application to call any phone number, including emergency numbers, without going through the Dialer user interface for the user to confirm the call being placed.
        /// </summary>
        internal static string CALL_PRIVILEGED {
            get {
                return ResourceManager.GetString("CALL_PRIVILEGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required to be able to access the camera device.
        /// </summary>
        internal static string CAMERA {
            get {
                return ResourceManager.GetString("CAMERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows an application to change whether an application component (other than its own) is enabled or not.
        /// </summary>
        internal static string CHANGE_COMPONENT_ENABLED_STATE {
            get {
                return ResourceManager.GetString("CHANGE_COMPONENT_ENABLED_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows an application to modify the current configuration, such as locale.
        /// </summary>
        internal static string CHANGE_CONFIGURATION {
            get {
                return ResourceManager.GetString("CHANGE_CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows applications to change network connectivity state.
        /// </summary>
        internal static string CHANGE_NETWORK_STATE {
            get {
                return ResourceManager.GetString("CHANGE_NETWORK_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows applications to enter Wi-Fi Multicast mode.
        /// </summary>
        internal static string CHANGE_WIFI_MULTICAST_STATE {
            get {
                return ResourceManager.GetString("CHANGE_WIFI_MULTICAST_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows applications to change Wi-Fi connectivity state.
        /// </summary>
        internal static string CHANGE_WIFI_STATE {
            get {
                return ResourceManager.GetString("CHANGE_WIFI_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing this setting requires an application restart..
        /// </summary>
        internal static string ChangeSettingRestart {
            get {
                return ResourceManager.GetString("ChangeSettingRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Update.
        /// </summary>
        internal static string CheckForUpdate {
            get {
                return ResourceManager.GetString("CheckForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Details.
        /// </summary>
        internal static string ClassDetails {
            get {
                return ResourceManager.GetString("ClassDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation for Class copied to clipboard (RTF).
        /// </summary>
        internal static string ClassDocumentationCopied {
            get {
                return ResourceManager.GetString("ClassDocumentationCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        internal static string Classes {
            get {
                return ResourceManager.GetString("Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Name.
        /// </summary>
        internal static string ClassName {
            get {
                return ResourceManager.GetString("ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Short Name.
        /// </summary>
        internal static string ClassShortName {
            get {
                return ResourceManager.GetString("ClassShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows an application to clear the caches of all installed applications on the device.
        /// </summary>
        internal static string CLEAR_APP_CACHE {
            get {
                return ResourceManager.GetString("CLEAR_APP_CACHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows an application to clear user data.
        /// </summary>
        internal static string CLEAR_APP_USER_DATA {
            get {
                return ResourceManager.GetString("CLEAR_APP_USER_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Snippets.
        /// </summary>
        internal static string CodeSnippets {
            get {
                return ResourceManager.GetString("CodeSnippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        internal static string Community {
            get {
                return ResourceManager.GetString("Community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows enabling/disabling location update notifications from the radio.
        /// </summary>
        internal static string CONTROL_LOCATION_UPDATES {
            get {
                return ResourceManager.GetString("CONTROL_LOCATION_UPDATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Full Path.
        /// </summary>
        internal static string CopyFullPath {
            get {
                return ResourceManager.GetString("CopyFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Name.
        /// </summary>
        internal static string CopyName {
            get {
                return ResourceManager.GetString("CopyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Names.
        /// </summary>
        internal static string CopyNames {
            get {
                return ResourceManager.GetString("CopyNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy RTF.
        /// </summary>
        internal static string CopyRTF {
            get {
                return ResourceManager.GetString("CopyRTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Text.
        /// </summary>
        internal static string CopyText {
            get {
                return ResourceManager.GetString("CopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have provided the correct details..
        /// </summary>
        internal static string CorrectDetails {
            get {
                return ResourceManager.GetString("CorrectDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not export settings to current directory. Check security on the folder..
        /// </summary>
        internal static string CouldNotExportSettings {
            get {
                return ResourceManager.GetString("CouldNotExportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks go to the following people for translation and testing assistance:.
        /// </summary>
        internal static string CreditThanks {
            get {
                return ResourceManager.GetString("CreditThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows an application to delete cache files.
        /// </summary>
        internal static string DELETE_CACHE_FILES {
            get {
                return ResourceManager.GetString("DELETE_CACHE_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows an application to delete packages.
        /// </summary>
        internal static string DELETE_PACKAGES {
            get {
                return ResourceManager.GetString("DELETE_PACKAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Snippet.
        /// </summary>
        internal static string DeleteSnippet {
            get {
                return ResourceManager.GetString("DeleteSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depends On.
        /// </summary>
        internal static string DependsOn {
            get {
                return ResourceManager.GetString("DependsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows low-level access to power management.
        /// </summary>
        internal static string DEVICE_POWER {
            get {
                return ResourceManager.GetString("DEVICE_POWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows applications to RW to diagnostic resources.
        /// </summary>
        internal static string DIAGNOSTIC {
            get {
                return ResourceManager.GetString("DIAGNOSTIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows applications to disable the keyguard.
        /// </summary>
        internal static string DISABLE_KEYGUARD {
            get {
                return ResourceManager.GetString("DISABLE_KEYGUARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doclet Version.
        /// </summary>
        internal static string DocletVersionNOTLibraryVersion {
            get {
                return ResourceManager.GetString("DocletVersionNOTLibraryVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document All.
        /// </summary>
        internal static string DocumentAll {
            get {
                return ResourceManager.GetString("DocumentAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Class.
        /// </summary>
        internal static string DocumentClass {
            get {
                return ResourceManager.GetString("DocumentClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documenting.
        /// </summary>
        internal static string Documenting {
            get {
                return ResourceManager.GetString("Documenting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Library.
        /// </summary>
        internal static string DocumentLibrary {
            get {
                return ResourceManager.GetString("DocumentLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        internal static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $10 (the price of one McDonalds meal) will keep me happy..
        /// </summary>
        internal static string DonateExample {
            get {
                return ResourceManager.GetString("DonateExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you considered donating?
        ///A small contribution will enable me to continue supporting the B4x community.
        ///Once you donate, you will not be asked again..
        /// </summary>
        internal static string DonateReason {
            get {
                return ResourceManager.GetString("DonateReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Community Data.
        /// </summary>
        internal static string DownloadCommunityData {
            get {
                return ResourceManager.GetString("DownloadCommunityData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows an application to retrieve state dump information from system services.
        /// </summary>
        internal static string DUMP {
            get {
                return ResourceManager.GetString("DUMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Class has the same ShortName as &apos;&lt;PARENTNAME&gt;.&lt;SHORTNAME&gt;&apos;.
        /// </summary>
        internal static string DuplicateClassName {
            get {
                return ResourceManager.GetString("DuplicateClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more classes within this Library has a duplicate ShortName.
        /// </summary>
        internal static string DuplicateClassNameInLibrary {
            get {
                return ResourceManager.GetString("DuplicateClassNameInLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Comment.
        /// </summary>
        internal static string EditComment {
            get {
                return ResourceManager.GetString("EditComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Description.
        /// </summary>
        internal static string EditDescription {
            get {
                return ResourceManager.GetString("EditDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Snippet.
        /// </summary>
        internal static string EditSnippet {
            get {
                return ResourceManager.GetString("EditSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address is in use already..
        /// </summary>
        internal static string EmailAddressInUse {
            get {
                return ResourceManager.GetString("EmailAddressInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable edits.
        /// </summary>
        internal static string EnableEdits {
            get {
                return ResourceManager.GetString("EnableEdits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Snippet Drag Drop.
        /// </summary>
        internal static string EnableSnippetDragDrop {
            get {
                return ResourceManager.GetString("EnableSnippetDragDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter search term.
        /// </summary>
        internal static string EnterSearchTerm {
            get {
                return ResourceManager.GetString("EnterSearchTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure you have entered a value for each, and try again..
        /// </summary>
        internal static string EnterValues {
            get {
                return ResourceManager.GetString("EnterValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        internal static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows an application to expand or collapse the status bar.
        /// </summary>
        internal static string EXPAND_STATUS_BAR {
            get {
                return ResourceManager.GetString("EXPAND_STATUS_BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as a manufacturer test application, running as the root user.
        /// </summary>
        internal static string FACTORY_TEST {
            get {
                return ResourceManager.GetString("FACTORY_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        internal static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        internal static string Fields {
            get {
                return ResourceManager.GetString("Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows access to the flashlight.
        /// </summary>
        internal static string FLASHLIGHT {
            get {
                return ResourceManager.GetString("FLASHLIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows an application to force a BACK operation on whatever is the top activity.
        /// </summary>
        internal static string FORCE_BACK {
            get {
                return ResourceManager.GetString("FORCE_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows access to the list of accounts in the Accounts Service.
        /// </summary>
        internal static string GET_ACCOUNTS {
            get {
                return ResourceManager.GetString("GET_ACCOUNTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows an application to find out the space used by any package.
        /// </summary>
        internal static string GET_PACKAGE_SIZE {
            get {
                return ResourceManager.GetString("GET_PACKAGE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows an application to get information about the currently or recently running tasks.
        /// </summary>
        internal static string GET_TASKS {
            get {
                return ResourceManager.GetString("GET_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string GUILanguage {
            get {
                return ResourceManager.GetString("GUILanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide BA Object If First Parameter.
        /// </summary>
        internal static string HideBAObjectIfFirstParameter {
            get {
                return ResourceManager.GetString("HideBAObjectIfFirstParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity.
        /// </summary>
        internal static string Identity {
            get {
                return ResourceManager.GetString("Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity created..
        /// </summary>
        internal static string IdentityCreated {
            get {
                return ResourceManager.GetString("IdentityCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity updated..
        /// </summary>
        internal static string IdentityUpdated {
            get {
                return ResourceManager.GetString("IdentityUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        internal static string Idle {
            get {
                return ResourceManager.GetString("Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Email Address..
        /// </summary>
        internal static string IncorrectEmail {
            get {
                return ResourceManager.GetString("IncorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Password..
        /// </summary>
        internal static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password or email address..
        /// </summary>
        internal static string IncorrectPasswordOrEmail {
            get {
                return ResourceManager.GetString("IncorrectPasswordOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Username..
        /// </summary>
        internal static string IncorrectUsername {
            get {
                return ResourceManager.GetString("IncorrectUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows applications to open Network sockets.
        /// </summary>
        internal static string INTERNET {
            get {
                return ResourceManager.GetString("INTERNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ios API.
        /// </summary>
        internal static string iosAPI {
            get {
                return ResourceManager.GetString("iosAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java API.
        /// </summary>
        internal static string JavaAPI {
            get {
                return ResourceManager.GetString("JavaAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        internal static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries.
        /// </summary>
        internal static string Libraries {
            get {
                return ResourceManager.GetString("Libraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        internal static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation for Library copied to clipboard (RTF).
        /// </summary>
        internal static string LibraryDocumentationCopied {
            get {
                return ResourceManager.GetString("LibraryDocumentationCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Paths.
        /// </summary>
        internal static string LibraryPaths {
            get {
                return ResourceManager.GetString("LibraryPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Selected; Choose a Class.
        /// </summary>
        internal static string LibrarySelectedChooseAClass {
            get {
                return ResourceManager.GetString("LibrarySelectedChooseAClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Community Comments.
        /// </summary>
        internal static string LoadingCommunityComments {
            get {
                return ResourceManager.GetString("LoadingCommunityComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Community Votes.
        /// </summary>
        internal static string LoadingCommunityVotes {
            get {
                return ResourceManager.GetString("LoadingCommunityVotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Libraries.
        /// </summary>
        internal static string LoadingLibraries {
            get {
                return ResourceManager.GetString("LoadingLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Library File.
        /// </summary>
        internal static string LoadingLibraryFile {
            get {
                return ResourceManager.GetString("LoadingLibraryFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load XML On Demand.
        /// </summary>
        internal static string LoadXMLOnDemand {
            get {
                return ResourceManager.GetString("LoadXMLOnDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        internal static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods.
        /// </summary>
        internal static string Methods {
            get {
                return ResourceManager.GetString("Methods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods Properties Fields.
        /// </summary>
        internal static string MethodsPropertiesFields {
            get {
                return ResourceManager.GetString("MethodsPropertiesFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods, Properties and Fields copied to clipboard.
        /// </summary>
        internal static string MethodsPropertiesFieldsCopied {
            get {
                return ResourceManager.GetString("MethodsPropertiesFieldsCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have Application Paths configured, but you have a backup copy of the configuration.  Load this configuration?.
        /// </summary>
        internal static string NoApplicationPaths {
            get {
                return ResourceManager.GetString("NoApplicationPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        internal static string Object {
            get {
                return ResourceManager.GetString("Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Wrapper.
        /// </summary>
        internal static string ObjectWrapper {
            get {
                return ResourceManager.GetString("ObjectWrapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a folder for the export..
        /// </summary>
        internal static string PleaseChooseAFolder {
            get {
                return ResourceManager.GetString("PleaseChooseAFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please configure options, including the folder where the B4x Libraries are installed.
        /// </summary>
        internal static string PleaseConfigureOptions {
            get {
                return ResourceManager.GetString("PleaseConfigureOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Confirm.
        /// </summary>
        internal static string PleaseConfirm {
            get {
                return ResourceManager.GetString("PleaseConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the file you want to import..
        /// </summary>
        internal static string PleaseSelectFileToImport {
            get {
                return ResourceManager.GetString("PleaseSelectFileToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Is Read Only.
        /// </summary>
        internal static string PropertyIsReadOnly {
            get {
                return ResourceManager.GetString("PropertyIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Is Read/Write.
        /// </summary>
        internal static string PropertyIsReadWrite {
            get {
                return ResourceManager.GetString("PropertyIsReadWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        internal static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Libraries.
        /// </summary>
        internal static string ReloadLibraries {
            get {
                return ResourceManager.GetString("ReloadLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Snippet.
        /// </summary>
        internal static string RemoveSnippet {
            get {
                return ResourceManager.GetString("RemoveSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove your vote for this Comment.
        /// </summary>
        internal static string RemoveYourVoteForThisComment {
            get {
                return ResourceManager.GetString("RemoveYourVoteForThisComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Value.
        /// </summary>
        internal static string ReturnValue {
            get {
                return ResourceManager.GetString("ReturnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTF copied to clipboard.
        /// </summary>
        internal static string RTFCopied {
            get {
                return ResourceManager.GetString("RTFCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search B4a Site.
        /// </summary>
        internal static string SearchB4aSite {
            get {
                return ResourceManager.GetString("SearchB4aSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search B4x Site.
        /// </summary>
        internal static string SearchB4xSite {
            get {
                return ResourceManager.GetString("SearchB4xSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search History.
        /// </summary>
        internal static string SearchHistory {
            get {
                return ResourceManager.GetString("SearchHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Search&gt;.
        /// </summary>
        internal static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Also.
        /// </summary>
        internal static string SeeAlso {
            get {
                return ResourceManager.GetString("SeeAlso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Name.
        /// </summary>
        internal static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Class_Globals.
        /// </summary>
        internal static string ShowClassGlobals {
            get {
                return ResourceManager.GetString("ShowClassGlobals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show DesignerCreateView.
        /// </summary>
        internal static string ShowDesignerCreateView {
            get {
                return ResourceManager.GetString("ShowDesignerCreateView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Empty Parentheses.
        /// </summary>
        internal static string ShowEmptyParentheses {
            get {
                return ResourceManager.GetString("ShowEmptyParentheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Full Typename.
        /// </summary>
        internal static string ShowFullTypename {
            get {
                return ResourceManager.GetString("ShowFullTypename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Labels.
        /// </summary>
        internal static string ShowLabels {
            get {
                return ResourceManager.GetString("ShowLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Property Get and Property Set.
        /// </summary>
        internal static string ShowPropertyGetAndSet {
            get {
                return ResourceManager.GetString("ShowPropertyGetAndSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Search Results In Library Class TreeView.
        /// </summary>
        internal static string ShowSearchResultsInLibraryClassTreeView {
            get {
                return ResourceManager.GetString("ShowSearchResultsInLibraryClassTreeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Void In Usage.
        /// </summary>
        internal static string ShowVoidInUsage {
            get {
                return ResourceManager.GetString("ShowVoidInUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippet text.
        /// </summary>
        internal static string SnippetText {
            get {
                return ResourceManager.GetString("SnippetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard XML File.
        /// </summary>
        internal static string StandardXMLFile {
            get {
                return ResourceManager.GetString("StandardXMLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay on top.
        /// </summary>
        internal static string StayOnTop {
            get {
                return ResourceManager.GetString("StayOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax.
        /// </summary>
        internal static string Syntax {
            get {
                return ResourceManager.GetString("Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text copied to clipboard.
        /// </summary>
        internal static string TextCopied {
            get {
                return ResourceManager.GetString("TextCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Class Depends On.
        /// </summary>
        internal static string ThisClassDependsOn {
            get {
                return ResourceManager.GetString("ThisClassDependsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Class Wraps.
        /// </summary>
        internal static string ThisClassWraps {
            get {
                return ResourceManager.GetString("ThisClassWraps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet address.
        /// </summary>
        internal static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Community Data.
        /// </summary>
        internal static string UseCommunityData {
            get {
                return ResourceManager.GetString("UseCommunityData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username does not exist..
        /// </summary>
        internal static string UsernameDoesNotExist {
            get {
                return ResourceManager.GetString("UsernameDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username saved to settings..
        /// </summary>
        internal static string UsernameSaved {
            get {
                return ResourceManager.GetString("UsernameSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Applicability.
        /// </summary>
        internal static string VersionApplicability {
            get {
                return ResourceManager.GetString("VersionApplicability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votes.
        /// </summary>
        internal static string Votes {
            get {
                return ResourceManager.GetString("Votes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (you).
        /// </summary>
        internal static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already voted on this comment.
        /// </summary>
        internal static string YouHaveAlreadyVoted {
            get {
                return ResourceManager.GetString("YouHaveAlreadyVoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Zero Dependencies].
        /// </summary>
        internal static string ZeroDependencies {
            get {
                return ResourceManager.GetString("ZeroDependencies", resourceCulture);
            }
        }
    }
}
