<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-windows7.0</TargetFramework>
		<SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion>7.0</TargetPlatformMinVersion>
		<UseWindowsForms>true</UseWindowsForms>
		<ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
		<ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
		<ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
		<PackageReference Include="MSTest.TestAdapter" Version="4.2.1" />
		<PackageReference Include="MSTest.TestFramework" Version="4.2.1" />
		<ProjectReference Include="..\AutoUpdater.NET\AutoUpdater.csproj" />
	</ItemGroup>
</Project>
