<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Platform Condition=" '$(Platform)' == '' ">x86</Platform>
		<OutputType>WinExe</OutputType>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<UseWindowsForms>true</UseWindowsForms>
		<ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
		<ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
		<ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\AutoUpdater.NET\AutoUpdater.csproj" />
	</ItemGroup>
</Project>